set -g status-bg colour255
set -g status-fg colour242
set -g status-left "#[fg=colour160]·#S· "
set -g status-right "#[fg=colour242]%H:%M #[fg=colour242]%d-%b-%y"
set -g pane-active-border-style fg=colour245
set -g pane-border-style fg=colour252
set -g mode-style 'fg=colour255,bg=colour33,bold'
set -g message-style 'fg=colour235,bg=colour255'
set -g message-command-style 'fg=colour235,bg=colour254'
set -g display-panes-active-colour colour33
set -g display-panes-colour colour244

setw -g window-status-current-style 'fg=colour235 bold'
setw -g window-status-style 'fg=colour244'
